--- 
javascripts: 
- base:
  - jquery.livequery
  - jquery_ujs
  - application
  - pretty_flash
  - toggle_summaries
- invoices:
  - invoices
  - auto_resize_textareas
  - edit_in_place
- new_invoice:
  - new_invoice_form
- friendly_time_select:
  - friendly_time_select

stylesheets: 
- base: 
  - application
  - pretty_flash
- invoices:
  - invoices
- invoice:
  - invoice
- calendar:
  - calendar
